#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

time-border:
        hour: 11
        minute : 0

spring:
  main:
    allow-circular-references : true
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        id.new_generator_mappings: false
        cache:
          queries: false
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  datasource:
    # ImMemory
         url: jdbc:h2:mem:app
         username: sa
         password:
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:app

  cache:
      jcache:
        config: classpath:ehcache.xml

  h2.console.enabled: true


